apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  name: {{ include "laravelChart.fullname" . }}-queue
  labels:
{{ include "laravelChart.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.queue.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "laravelChart.name" . }}-queue
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "laravelChart.name" . }}-queue
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "laravelChart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-queue
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.queue.image.repository }}:{{ .Values.queue.image.tag }}"
          imagePullPolicy: {{ .Values.queue.image.pullPolicy }}
          {{- with .Values.queue.configName }}
          envFrom:
            - configMapRef:
                name: {{ .Values.queue.configName }}
          {{- end}}
          env:
            - name: CONTAINER_ROLE
              value: "queue"

      resources:
        {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
