{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "laravelChart.serviceAccountName" . }}
  labels:
{{ include "laravelChart.labels" . | indent 4 }}
{{- end -}}
